version: '2'
services:
    svcb-app:
        image: svcb
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://svcb-mysql:3306/svcb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    svcb-mysql:
        extends:
            file: mysql.yml
            service: svcb-mysql
