version: '2'
services:
    demouaa-app:
        image: demouaa
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://demouaa-mysql:3306/demouaa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    demouaa-mysql:
        extends:
            file: mysql.yml
            service: demouaa-mysql
